.TH GTI 6 2013-04-16

.SH NAME
\fBpopel\fP \- Humorous typo-based sopel runner; drives a car over the terminal.

.SH DESCRIPTION
\fBpopel\fP is intended to catch accidental typos of 'popel' instead of 'sopel'. It
displays an animation of a car driving by, and then launches sopel. Any
parameters or arguments given to \fBpopel\fP will be passed through to sopel.

The car image is derived from the look of an old VW Golf GTI.

.SH ENVIRONMENT
\fBpopel\fP respects the GIT environment variable. If GIT is set, its value will
be used to launch sopel after the animation finishes, instead of searching for
sopel in your PATH.

.SH SEE ALSO
\fBsopel\fP(1), \fBsl\fP(6)

.SH AUTHOR
\fBpopel\fP was written by Richard Wossal <richard@r-wos.org>. This manual was
written by Felix Crux <felixc@felixcrux.com> for the Debian project, but may
be used by others under the same terms as \fBpopel\fP itself.
